language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy
install:
  - pip uninstall -y nose
  - pip install --use-mirrors "coverage >= 3.3"
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.5" ] || [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then
    pip install --use-mirrors unittest2; fi;
script:
  - python setup.py build_tests || python setup.py egg_info; python selftest.py
